### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by psolymos** [psolymos/speciesarea#1]
- [ ] write scripts to convert old tables to new format
- [ ] add in new entries
- [ ] write scripts to generate auto-content (appendix for data paper)
- [ ] write data paper for GEB
